### ISSUE TITLE
Tic-tac-toe game in React

### ISSUE THREAD

**Issue by AkshitSalwan** [Sahani99/Mini-projects-Hacktoberfest2024#17]
Can add a tic-tac-toe game using React.js. Kindly assign me this issue with hacktoberfest labels.

**Comment by BaniSinghgithub** [comment]
hello @Sahani99 , pls assign this work to me

**Comment by Sahani99** [comment]
add a tic-tac-toe game using React.js

**Comment by BaniSinghgithub** [comment]
hello @Sahani99 , can you assign this work to me also.

**Comment by himasnhu018** [comment]
assign me that project

**Comment by AkshitSalwan** [comment]
You can close this request as someone has already added one
